"""
RSI Mean Reversion signal strategy.

Responsibilities:
- Evaluate RSI indicator values for mean reversion trading signals.
- Generate LONG signals when RSI crosses above oversold threshold.
- Generate SHORT signals when RSI crosses below overbought threshold.
- Compute signal strength based on RSI swing magnitude.
- Declare RSI as a required indicator with configurable period.

Does NOT:
- Manage positions or execute orders.
- Evaluate risk gates (service layer responsibility).
- Persist signals (repository layer responsibility).

Dependencies:
- libs.contracts.interfaces.signal_strategy: SignalStrategyInterface
- libs.contracts.signal: Signal, SignalDirection, SignalStrength, SignalType
- libs.contracts.indicator: IndicatorRequest, IndicatorResult
- libs.contracts.market_data: Candle
- libs.contracts.execution: PositionSnapshot
- services.worker.strategies._base: build_signal
- structlog: debug logging

Error conditions:
- Returns None if RSI values contain fewer than 2 valid (non-NaN) values at end.
- Returns None if no cross-threshold condition is met.

Example:
    strategy = RSIMeanReversionStrategy(
        deployment_id="deploy-001",
        rsi_period=14,
        oversold=30.0,
        overbought=70.0,
    )
    signal = strategy.evaluate("AAPL", candles, indicators, None, correlation_id="c1")
    # Returns Signal with LONG direction if RSI crosses above oversold, or None.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
import structlog

from libs.contracts.indicator import IndicatorRequest
from libs.contracts.interfaces.signal_strategy import SignalStrategyInterface
from libs.contracts.signal import SignalDirection, SignalStrength, SignalType
from services.worker.strategies._base import build_signal

if TYPE_CHECKING:
    from libs.contracts.execution import PositionSnapshot
    from libs.contracts.indicator import IndicatorResult
    from libs.contracts.market_data import Candle
    from libs.contracts.signal import Signal

logger = structlog.get_logger(__name__)


class RSIMeanReversionStrategy(SignalStrategyInterface):
    """
    RSI Mean Reversion signal strategy.

    Generates trading signals based on RSI (Relative Strength Index) moving
    into or out of extreme zones (oversold/overbought). A LONG signal fires
    when RSI crosses above the oversold threshold from below, indicating
    potential upward reversal. A SHORT signal fires when RSI crosses below
    the overbought threshold from above, indicating potential downward reversal.

    Signal strength is determined by the magnitude of the RSI swing (distance
    between current RSI and the extreme point in the lookback window):
    - STRONG: swing >= strong_swing threshold
    - MODERATE: swing >= moderate_swing threshold
    - WEAK: swing < moderate_swing threshold

    Confidence is computed as min(swing / strong_swing, 1.0) clamped to [0.0, 1.0].

    Responsibilities:
    - Evaluate RSI values for mean reversion conditions.
    - Compute swing magnitude and signal strength.
    - Declare RSI as a required indicator.
    - Expose strategy identity and configuration.

    Does NOT:
    - Manage positions or execute orders.
    - Evaluate risk gates.
    - Persist signals.

    Dependencies:
    - Injected deployment_id from constructor.
    - IndicatorResult with RSI values keyed as f"RSI_{period}".
    - Candles list for timing metadata.

    Raises:
    - No exceptions; returns None if conditions not met.

    Example:
        strategy = RSIMeanReversionStrategy(
            deployment_id="deploy-001",
            rsi_period=14,
            oversold=30.0,
            overbought=70.0,
            strong_swing=15.0,
            moderate_swing=8.0,
        )
        reqs = strategy.required_indicators()
        # [IndicatorRequest(indicator_name="RSI", params={"period": 14})]

        signal = strategy.evaluate("AAPL", candles, indicators, None, correlation_id="c1")
        # Returns Signal with LONG direction if RSI(14) crosses above 30, or None.
    """

    def __init__(
        self,
        deployment_id: str,
        rsi_period: int = 14,
        oversold: float = 30.0,
        overbought: float = 70.0,
        strong_swing: float = 15.0,
        moderate_swing: float = 8.0,
        supported_symbols: list[str] | None = None,
    ) -> None:
        """
        Initialize an RSI Mean Reversion strategy.

        Args:
            deployment_id: Deployment context ID for signals generated by this strategy.
            rsi_period: Lookback period for RSI calculation (default 14).
            oversold: RSI oversold threshold below which reversals are expected (default 30).
            overbought: RSI overbought threshold above which reversals are expected (default 70).
            strong_swing: RSI swing magnitude considered strong (default 15.0).
            moderate_swing: RSI swing magnitude considered moderate (default 8.0).
            supported_symbols: List of symbols this strategy can trade (None = all).

        Example:
            strategy = RSIMeanReversionStrategy(
                deployment_id="deploy-prod-01",
                rsi_period=14,
                oversold=30.0,
                overbought=70.0,
            )
        """
        self._deployment_id = deployment_id
        self._rsi_period = rsi_period
        self._oversold = oversold
        self._overbought = overbought
        self._strong_swing = strong_swing
        self._moderate_swing = moderate_swing
        self._supported_symbols = supported_symbols or []

    @property
    def strategy_id(self) -> str:
        """Unique identifier for this strategy."""
        return "rsi-mean-reversion"

    @property
    def name(self) -> str:
        """Human-readable name for this strategy."""
        return "RSI Mean Reversion"

    @property
    def supported_symbols(self) -> list[str]:
        """List of symbols this strategy can trade (empty = all)."""
        return self._supported_symbols

    def required_indicators(self) -> list[IndicatorRequest]:
        """
        Declare the RSI indicator required by this strategy.

        Returns:
            List containing a single IndicatorRequest for RSI with the
            configured period parameter.

        Example:
            reqs = strategy.required_indicators()
            # [IndicatorRequest(indicator_name="RSI", params={"period": 14})]
        """
        return [
            IndicatorRequest(
                indicator_name="RSI",
                params={"period": self._rsi_period},
            )
        ]

    def evaluate(
        self,
        symbol: str,
        candles: list[Candle],
        indicators: dict[str, IndicatorResult],
        current_position: PositionSnapshot | None,
        *,
        correlation_id: str,
    ) -> Signal | None:
        """
        Evaluate RSI for mean reversion signals.

        Checks if RSI has crossed a threshold (oversold or overbought) from
        the opposite side, indicating a potential reversal. Computes signal
        strength based on the swing magnitude and confidence based on the
        swing relative to the strong threshold.

        Args:
            symbol: Ticker symbol being evaluated.
            candles: Recent candle data for the symbol.
            indicators: Pre-computed indicator results keyed by indicator name,
                must contain key f"RSI_{period}" with IndicatorResult.
            current_position: Current position snapshot (None if flat).
            correlation_id: Request correlation ID for tracing.

        Returns:
            A Signal with LONG direction if RSI crosses above oversold,
            A Signal with SHORT direction if RSI crosses below overbought,
            None if no cross-threshold condition is met or insufficient data.

        Example:
            # RSI crosses from 28 → 32 (crosses above oversold 30)
            signal = strategy.evaluate(
                "AAPL",
                candles,
                {"RSI_14": IndicatorResult(values=np.array([..., 28, 32]))},
                None,
                correlation_id="c1",
            )
            # Returns Signal with direction=LONG, strength=MODERATE, confidence~0.67
        """
        logger.debug(
            "evaluating_rsi_strategy",
            extra={
                "operation": "evaluate_rsi_mean_reversion",
                "symbol": symbol,
                "rsi_period": self._rsi_period,
                "correlation_id": correlation_id,
            },
        )

        # Retrieve RSI values from indicators dict
        rsi_key = f"RSI_{self._rsi_period}"
        if rsi_key not in indicators:
            logger.debug(
                "missing_rsi_indicator",
                extra={
                    "operation": "evaluate_rsi_mean_reversion",
                    "symbol": symbol,
                    "expected_key": rsi_key,
                    "correlation_id": correlation_id,
                },
            )
            return None

        indicator_result = indicators[rsi_key]
        rsi_values = indicator_result.values

        if rsi_values is None or not isinstance(rsi_values, np.ndarray):
            logger.debug(
                "invalid_rsi_values_type",
                extra={
                    "operation": "evaluate_rsi_mean_reversion",
                    "symbol": symbol,
                    "correlation_id": correlation_id,
                },
            )
            return None

        # Filter out NaN values and check we have at least 2 valid values
        valid_mask = ~np.isnan(rsi_values)
        valid_values = rsi_values[valid_mask]

        if len(valid_values) < 2:
            logger.debug(
                "insufficient_rsi_data",
                extra={
                    "operation": "evaluate_rsi_mean_reversion",
                    "symbol": symbol,
                    "valid_rsi_count": len(valid_values),
                    "correlation_id": correlation_id,
                },
            )
            return None

        # Get the last two valid RSI values (previous bar and current bar)
        rsi_prev = valid_values[-2]
        rsi_curr = valid_values[-1]

        logger.debug(
            "rsi_values_retrieved",
            extra={
                "operation": "evaluate_rsi_mean_reversion",
                "symbol": symbol,
                "rsi_prev": float(rsi_prev),
                "rsi_curr": float(rsi_curr),
                "oversold": self._oversold,
                "overbought": self._overbought,
                "correlation_id": correlation_id,
            },
        )

        # Determine signal direction and check for threshold crossover
        signal_direction: SignalDirection | None = None

        # LONG signal: RSI crosses above oversold from below
        if rsi_prev < self._oversold and rsi_curr >= self._oversold:
            signal_direction = SignalDirection.LONG
            logger.debug(
                "long_signal_condition_met",
                extra={
                    "operation": "evaluate_rsi_mean_reversion",
                    "symbol": symbol,
                    "rsi_prev": float(rsi_prev),
                    "rsi_curr": float(rsi_curr),
                    "correlation_id": correlation_id,
                },
            )

        # SHORT signal: RSI crosses below overbought from above
        elif rsi_prev > self._overbought and rsi_curr <= self._overbought:
            signal_direction = SignalDirection.SHORT
            logger.debug(
                "short_signal_condition_met",
                extra={
                    "operation": "evaluate_rsi_mean_reversion",
                    "symbol": symbol,
                    "rsi_prev": float(rsi_prev),
                    "rsi_curr": float(rsi_curr),
                    "correlation_id": correlation_id,
                },
            )

        if signal_direction is None:
            logger.debug(
                "no_signal_rsi_neutral",
                extra={
                    "operation": "evaluate_rsi_mean_reversion",
                    "symbol": symbol,
                    "rsi_curr": float(rsi_curr),
                    "correlation_id": correlation_id,
                },
            )
            return None

        # Compute swing magnitude and signal strength
        # For LONG: swing from minimum RSI in last 5 bars up to current
        # For SHORT: swing from maximum RSI in last 5 bars down to current
        if signal_direction == SignalDirection.LONG:
            # Look at last 5 bars' RSI values (or fewer if not available)
            lookback_window = min(5, len(valid_values))
            recent_values = valid_values[-lookback_window:]
            min_rsi = np.nanmin(recent_values)
            swing_magnitude = rsi_curr - min_rsi
        else:  # SHORT
            lookback_window = min(5, len(valid_values))
            recent_values = valid_values[-lookback_window:]
            max_rsi = np.nanmax(recent_values)
            swing_magnitude = max_rsi - rsi_curr

        # Determine signal strength based on swing magnitude
        if swing_magnitude >= self._strong_swing:
            strength = SignalStrength.STRONG
        elif swing_magnitude >= self._moderate_swing:
            strength = SignalStrength.MODERATE
        else:
            strength = SignalStrength.WEAK

        # Compute confidence as normalized swing magnitude
        confidence = min(float(swing_magnitude) / self._strong_swing, 1.0)
        confidence = max(0.0, confidence)  # Clamp to [0.0, 1.0]

        logger.debug(
            "rsi_swing_computed",
            extra={
                "operation": "evaluate_rsi_mean_reversion",
                "symbol": symbol,
                "swing_magnitude": float(swing_magnitude),
                "strength": strength.value,
                "confidence": confidence,
                "correlation_id": correlation_id,
            },
        )

        # Build and return the signal
        signal = build_signal(
            strategy_id=self.strategy_id,
            deployment_id=self._deployment_id,
            symbol=symbol,
            direction=signal_direction,
            signal_type=SignalType.ENTRY,
            strength=strength,
            confidence=confidence,
            indicators_used={
                f"rsi_{self._rsi_period}_prev": float(rsi_prev),
                f"rsi_{self._rsi_period}_curr": float(rsi_curr),
            },
            bar_timestamp=candles[-1].timestamp,
            correlation_id=correlation_id,
        )

        logger.debug(
            "rsi_signal_generated",
            extra={
                "operation": "evaluate_rsi_mean_reversion",
                "symbol": symbol,
                "signal_id": signal.signal_id,
                "direction": signal.direction.value,
                "strength": signal.strength.value,
                "correlation_id": correlation_id,
            },
        )

        return signal
