"""
Signal contracts for trading signal generation and evaluation.

Responsibilities:
- Define signal direction, type, and strength taxonomies.
- Define immutable Signal model produced by signal strategies.
- Define RiskGateResult for individual gate outcomes.
- Define SignalEvaluation for post-risk-gate processed signals.
- Define SignalStats for strategy performance aggregation.

Does NOT:
- Implement signal generation logic (strategy layer responsibility).
- Evaluate risk gates (service layer responsibility).
- Persist signals (repository layer responsibility).

Dependencies:
- pydantic: BaseModel, Field
- datetime, decimal, enum: standard library

Error conditions:
- Pydantic ValidationError raised on invalid field values.

Example:
    from libs.contracts.signal import (
        Signal,
        SignalDirection,
        SignalEvaluation,
        SignalStrength,
        SignalType,
    )

    signal = Signal(
        signal_id="01HTEST0000000000000000001",
        strategy_id="strat-sma-cross",
        deployment_id="deploy-001",
        symbol="AAPL",
        direction=SignalDirection.LONG,
        signal_type=SignalType.ENTRY,
        strength=SignalStrength.STRONG,
        confidence=0.85,
        indicators_used={"sma_fast": 175.50, "sma_slow": 170.20},
        bar_timestamp=datetime(2026, 4, 13, 14, 30, tzinfo=timezone.utc),
        generated_at=datetime(2026, 4, 13, 14, 30, 1, tzinfo=timezone.utc),
        correlation_id="corr-001",
    )
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class SignalDirection(str, Enum):  # noqa: UP042 — StrEnum requires Python 3.11+
    """
    Direction of a trading signal.

    - LONG: buy / go long.
    - SHORT: sell short.
    - FLAT: exit all positions (directionally neutral).

    Example:
        direction = SignalDirection.LONG
    """

    LONG = "long"
    SHORT = "short"
    FLAT = "flat"


class SignalStrength(str, Enum):  # noqa: UP042 — StrEnum requires Python 3.11+
    """
    Relative strength of a trading signal.

    Used by the evaluation pipeline to size positions proportionally.

    - STRONG: high conviction, maximum position size.
    - MODERATE: medium conviction, standard position size.
    - WEAK: low conviction, reduced position size or skip.

    Example:
        strength = SignalStrength.STRONG
    """

    STRONG = "strong"
    MODERATE = "moderate"
    WEAK = "weak"


class SignalType(str, Enum):  # noqa: UP042 — StrEnum requires Python 3.11+
    """
    Classification of what the signal intends to do.

    - ENTRY: open a new position.
    - EXIT: close an existing position entirely.
    - SCALE_IN: add to an existing position.
    - SCALE_OUT: reduce an existing position.
    - STOP_ADJUSTMENT: move the stop loss level.

    Example:
        sig_type = SignalType.ENTRY
    """

    ENTRY = "entry"
    EXIT = "exit"
    SCALE_IN = "scale_in"
    SCALE_OUT = "scale_out"
    STOP_ADJUSTMENT = "stop_adjustment"


# ---------------------------------------------------------------------------
# Domain models
# ---------------------------------------------------------------------------


class Signal(BaseModel):
    """
    Immutable trading signal produced by a signal strategy.

    Represents a single actionable market insight generated by evaluating
    candle data and technical indicators. Signals flow through risk gates
    before being executed.

    Attributes:
        signal_id: Unique identifier (ULID).
        strategy_id: ID of the originating strategy.
        deployment_id: Deployment context for this signal.
        symbol: Ticker symbol.
        direction: Long, short, or flat.
        signal_type: Entry, exit, scale_in, scale_out, or stop_adjustment.
        strength: Strong, moderate, or weak.
        suggested_entry: Suggested entry price (None if market order).
        suggested_stop: Suggested stop-loss price.
        suggested_target: Suggested take-profit price.
        confidence: Confidence level [0.0, 1.0].
        indicators_used: Indicator name → value at signal time.
        bar_timestamp: Timestamp of the bar that triggered the signal.
        generated_at: When the signal was generated.
        metadata: Arbitrary strategy-specific metadata.
        correlation_id: Request correlation ID for tracing.

    Example:
        signal = Signal(
            signal_id="01HTEST0000000000000000001",
            strategy_id="strat-sma-cross",
            deployment_id="deploy-001",
            symbol="AAPL",
            direction=SignalDirection.LONG,
            signal_type=SignalType.ENTRY,
            strength=SignalStrength.STRONG,
            confidence=0.85,
            indicators_used={"sma_fast": 175.50},
            bar_timestamp=datetime(2026, 4, 13, 14, 30, tzinfo=timezone.utc),
            generated_at=datetime(2026, 4, 13, 14, 30, 1, tzinfo=timezone.utc),
            correlation_id="corr-001",
        )
    """

    model_config = {"frozen": True}

    signal_id: str = Field(
        ..., min_length=1, max_length=255, description="Unique signal identifier (ULID)"
    )
    strategy_id: str = Field(
        ..., min_length=1, max_length=255, description="Originating strategy ID"
    )
    deployment_id: str = Field(
        ..., min_length=1, max_length=255, description="Deployment context ID"
    )
    symbol: str = Field(..., min_length=1, max_length=20, description="Ticker symbol")
    direction: SignalDirection = Field(..., description="Signal direction (long/short/flat)")
    signal_type: SignalType = Field(
        ..., description="Signal type (entry/exit/scale_in/scale_out/stop_adjustment)"
    )
    strength: SignalStrength = Field(..., description="Signal strength (strong/moderate/weak)")
    suggested_entry: Decimal | None = Field(default=None, description="Suggested entry price")
    suggested_stop: Decimal | None = Field(default=None, description="Suggested stop-loss price")
    suggested_target: Decimal | None = Field(
        default=None, description="Suggested take-profit price"
    )
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence level [0.0, 1.0]")
    indicators_used: dict[str, float] = Field(
        default_factory=dict, description="Indicator name → value at signal time"
    )
    bar_timestamp: datetime = Field(..., description="Timestamp of the triggering bar")
    generated_at: datetime = Field(..., description="When the signal was generated (UTC)")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Strategy-specific metadata")
    correlation_id: str = Field(..., min_length=1, description="Request correlation ID")

    @field_validator("symbol")
    @classmethod
    def _normalize_symbol(cls, v: str) -> str:
        """Normalize symbol to uppercase."""
        return v.upper()


class RiskGateResult(BaseModel):
    """
    Result of a single risk gate evaluation.

    Attributes:
        gate_name: Name of the risk gate (e.g. "max_position_size", "drawdown_limit").
        passed: Whether the signal passed this gate.
        details: Gate-specific details (thresholds, computed values, reasons).

    Example:
        result = RiskGateResult(
            gate_name="max_position_size",
            passed=True,
            details={"max_allowed": 1000, "requested": 500},
        )
    """

    model_config = {"frozen": True}

    gate_name: str = Field(..., min_length=1, description="Risk gate name")
    passed: bool = Field(..., description="Whether the signal passed this gate")
    details: dict[str, Any] = Field(default_factory=dict, description="Gate-specific details")


class SignalEvaluation(BaseModel):
    """
    Result of running a signal through the risk gate pipeline.

    Captures the signal, whether it was approved, individual gate results,
    position sizing output, and any rejection reason.

    Attributes:
        signal: The original signal being evaluated.
        approved: Whether the signal passed all risk gates.
        risk_gate_results: Individual gate outcomes.
        position_size: Computed position size (None if rejected).
        adjusted_stop: Risk-adjusted stop-loss price (None if rejected).
        rejection_reason: Human-readable rejection reason (None if approved).
        evaluated_at: When the evaluation was performed (UTC).

    Example:
        evaluation = SignalEvaluation(
            signal=signal,
            approved=True,
            risk_gate_results=[gate_result],
            position_size=Decimal("500"),
            adjusted_stop=Decimal("168.50"),
            rejection_reason=None,
            evaluated_at=datetime.now(tz=timezone.utc),
        )
    """

    model_config = {"frozen": True}

    signal: Signal
    approved: bool
    risk_gate_results: list[RiskGateResult] = Field(default_factory=list)
    position_size: Decimal | None = None
    adjusted_stop: Decimal | None = None
    rejection_reason: str | None = None
    evaluated_at: datetime


class SignalStats(BaseModel):
    """
    Aggregated signal statistics for a strategy over a time window.

    Used for strategy performance monitoring and dashboard display.

    Attributes:
        strategy_id: Strategy being summarised.
        total_signals: Total signals generated.
        approved_signals: Signals that passed risk gates.
        rejected_signals: Signals rejected by risk gates.
        long_signals: Number of long-direction signals.
        short_signals: Number of short-direction signals.
        flat_signals: Number of flat-direction signals.
        strong_signals: Number of strong-strength signals.
        moderate_signals: Number of moderate-strength signals.
        weak_signals: Number of weak-strength signals.
        avg_confidence: Average confidence across all signals.
        since: Start of the statistics window.
        until: End of the statistics window.

    Example:
        stats = SignalStats(
            strategy_id="strat-sma-cross",
            total_signals=100,
            approved_signals=80,
            rejected_signals=20,
            long_signals=55,
            short_signals=40,
            flat_signals=5,
            strong_signals=30,
            moderate_signals=50,
            weak_signals=20,
            avg_confidence=0.72,
            since=datetime(2026, 4, 12, tzinfo=timezone.utc),
            until=datetime(2026, 4, 13, tzinfo=timezone.utc),
        )
    """

    strategy_id: str
    total_signals: int = Field(..., ge=0)
    approved_signals: int = Field(..., ge=0)
    rejected_signals: int = Field(..., ge=0)
    long_signals: int = Field(default=0, ge=0)
    short_signals: int = Field(default=0, ge=0)
    flat_signals: int = Field(default=0, ge=0)
    strong_signals: int = Field(default=0, ge=0)
    moderate_signals: int = Field(default=0, ge=0)
    weak_signals: int = Field(default=0, ge=0)
    avg_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    since: datetime
    until: datetime
